language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
  - '9'
  
# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

script:
  - npm run test
  - npm run test:e2e

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: npm run semantic-release
    - stage: coverage
      script: npm run coverage:upload
