language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

script: npm run $COMMAND
env:
  matrix:
    - COMMAND=test
    - COMMAND=test:e2e
    - COMMAND=coverage:upload

after_success:
  - npm run semantic-release
